### ISSUE TITLE
ability to pretty-print non http requests

### ISSUE THREAD

**Issue by sdalezman** [beme/abide#33]
It would be awesome to able to be able to specify that you want to assert any arbitrary struct via it's json representation and to pretty print that struct in the snapshot. Right now instead I rely on encoding the struct and then passing it to AssertReader which doesn't pretty print the struct which makes comparisons between snapshots and to visualization json results difficult for large responses.

Use cases for this are larger structs that I would love to be able to assert via json (they never pass through an http endpoint).

I haven't looked through the internals of abide, but would be happy to take a look if it was something that you're interested in adding and we can agree on a correct interface for such an assertion

**Comment by sjkaliski** [comment]
Included is an [Assertable](https://godoc.org/github.com/beme/abide#Assertable) interface. Any type that implements `String() string` can make use of it via [abide.Assert](https://godoc.org/github.com/beme/abide#Assert).

@sdalezman lmk if this is what you're looking for (in which case, let's definitely improve documentation around it), otherwise up to look into a better solution.

For example

```go
// main.go
package main

import "encoding/json"

type Thing struct {
	A string `json:"a"`
	B struct {
		C int `json:"c`
	} `json:"b"`
}

func (t *Thing) String() string {
	data, _ := json.MarshalIndent(t, "", "  ")
	return string(data)
}
```

```go
// main_test.go
package main

import (
	"testing"

	"github.com/beme/abide"
)

func TestThing(t *testing.T) {
	thing := new(Thing)
	thing.A = "foo"
	thing.B.C = 123

	abide.Assert(t, "assertable", thing)
}
```

```
// abide.snapshot
/* snapshot: assertable */
{
  "a": "foo",
  "b": {
    "C": 123
  }
}
```

**Comment by sdalezman** [comment]
@sjkaliski I need to think about it a little bit more, but my general problem with the string interface is that it assumes that every struct that I want to assert via a snapshot should have a string interface that marshals to json.

For example, a lot of times for internal structs that process a lot of data we have custom string methods that drop in values for a struct that may not match exactly what you would want to marshal to json, but if an error did occur you want to be able to log that struct to see the values that it provides. 

With that in mind maybe we should make a decision that any struct that we want to be cleanly asserted via json we implement the string method as above

**Comment by sjkaliski** [comment]
Got it, so in your example, you have something like:

```
type Person struct {
  First string
  Last string
}

func (p *Person) String() string {
  return fmt.Sprintf("%s %s", p.First, p.Last)
}
```

But want your snapshot to be in the JSON format? And b/c you're already implementing `String()` for another use case, you're running into the issue?

**Comment by sjkaliski** [comment]
We could include the below method which would enable comparison to any string (you could also image this extending to other types).

```go
func AssertString(t *testing.T, id, data string)
```

Tests would then look like...

```go
data, _ := json.MarshalIndent(object, "", "  ")
abide.AssertString(t, "my snapshot", string(data))
```

**Comment by sdalezman** [comment]
Yea that's exactly the issue. There are some values in structs that we may want to log in our logs, but that we don't want to return via json if that makes sense

**Comment by sdalezman** [comment]
The other issue with the String interface is that let's say you have a function like this 

``` 
// person.go
type Person struct {
  First string `json:"first"`
  Last  string `json:"last"`
}

func (p *Person) String() string {
  data, _ := json.MarshalIndent(t, "", "  ")
   return string(data)
}

func GetAllPeople() []*Person {
   // some function to return all peeps
}

// person_test.go
func TestGetAllPeople(t *testing.T) {
   people := GetAllPeople()
   // will cause an error bec []*Person doesn't implement string
   abide.Assert(t, "get-peeps", people)
}
```

we have a lot of functions that return array of results in our models bec a lot of our api's combine group those apis together in one json response. For some of those functions we need a bunch of unit tests and have been asserting on the array which is really valuable

**Comment by sjkaliski** [comment]
If you're regularly interacting with `[]*Person`, can create a `People` or `PersonList` type, and attach a `String() string` method to it.

```go
type People []*Person

func (p *People) String() string {
  data, _ := json.MarshalIndent(p, "", "  ")
  return string(data)
}

// person_test.go
func TestGetAllPeople(t *testing.T) {
   people := GetAllPeople()
   // will cause an error bec []*Person doesn't implement string
   abide.Assert(t, "get-peeps", People(people))
}
```

**Comment by sdalezman** [comment]
Yea that makes sense. Went with a slightly different approach so that it's a bit more drop in for our needs above 

``` golang

// AbideUtil is a convenience util to to assert interfaces via abide that pretty print
type AbideUtil struct {
	Val interface{}
}

func (au *AbideUtil) String() string {
	data, _ := json.MarshalIndent(au.Val, "", "    ")
	return string(data)
}

// person_test.go
func TestGetAllPeople(t *testing.T) {
     people := GetAllPeople()
     abide.Assert(t, "get-peeps", AbideUtil{Val: people}) 
}
```

That allows us to more seamlessly drop in abide pretty printing where needed without having to pollute our code with types and method definitions and still accounts for the above not needing an `AssertString`

**Comment by sjkaliski** [comment]
Nice! Well I'm gonna close this issue for now. It may be helpful to improve the docs to include these kinds of examples. At the moment they are hidden deep in the example project / godoc. I've opened #36 as reference.
