### ISSUE TITLE
json unmarshaling asserts an error when using json Encoding 

### ISSUE THREAD

**Issue by sdalezman** [beme/abide#34]
The hard coded implementation in assert.go for parsing json responses breaks when using `json.NewEncoder([insert-my-struct]).Enocde(w)`. It asserts that 

To reproduce: 
``` golang 
type myStruct struct {
    Message `json:"message"`
}

func myHandler(w http.ResponseWriter, r *http.Request) {
    m := myStruct{
        Message: "hello abide"
    }
    json.NewEncoder(w).Encode(&m)
}
```

if you call assert http response on the above in some test: `abide.AssertHTTPResponse(t, name, w.Result())`, assert will return an error for `unexpected end of JSON input`. This is because there's a new line that seems to be returned from `httputil.DumpResponse` on the json response when using `NewEncoder` vs using `json.Marshal` and writing bytes. 

assert.go seems to be manually parsing the lines to determine the body, instead it probably makes more sense to actually read the properties from the response rather than the dump from httputil (I think there are a few cases where the dump won't always be consistent - but can't remember off the top of my head)

**Comment by sjkaliski** [comment]
Thanks for pointing this out! Was able to reproduce. This seems to be the culprit -->

https://github.com/beme/abide/blob/d831b87e3d654fbe84107933b56a60f0dab81aa8/assert.go#L46

The below change should make it work:

```go
lines := strings.Split(strings.TrimSpace(data), "\n")
```

I'm inclined to use the built in http dump unless there is a desire to include information which is not provided by that method.

**Comment by sdalezman** [comment]
thanks for the quick turnaround. there's definitely some information lost, but I think for the purposes of the snapshot makes sense!
