### ISSUE TITLE
Config for HTTP headers

### ISSUE THREAD

**Issue by rafaeljusto** [beme/abide#43]
Is it possible to replace a dynamic generated HTTP header using the [config](https://github.com/beme/abide#config)? I have an Etag HTTP header that is different every time I receive the response (time based).

**Comment by sjkaliski** [comment]
@rafaeljusto 👋 at the moment, the config only applies to the body of the response, though it could certainly be expanded to support headers as well. Perhaps something like this:

```
{
  "defaults": {
    "ETag": "default-etag-value"
  }
}
```

PR welcome!

Alternatively, a common pattern I've seen with this library is to use mocks for dynamic values like time, uuid's, etc within your tests.
