### ISSUE TITLE
Make snapshots concurrency safe

### ISSUE THREAD

**Issue by alexhornbake** [beme/abide#45]
I may tackle this one, but want to raise here first.

I think it would be worth converting `snapshots map[snapshotID]*snapshot` to use `sync.Map`, or perhaps just use a mutex to protect it. Wondering if there is a preference for minimum golang version that should be targeted, since sync.Map was introduced in golang 1.9. Thoughts?

For context, my use case is a set of tests that assert snapshots from multiple concurrent goroutines. As written, it hits the error: `fatal error: concurrent map writes` while updating snapshots on `github.com/beme/abide/abide.go:230`.

**Comment by sjkaliski** [comment]
@alexhornbake go for it! 1.9 is a sufficient minimum version.

**Comment by sjkaliski** [comment]
@alexhornbake thoughts? Should be ok now that we dropped 1.8.x support.

**Comment by sjkaliski** [comment]
@alexhornbake good to close?

**Comment by alexhornbake** [comment]
@sjkaliski yup!

**Comment by alexhornbake** [comment]
@sjkaliski yup!
